### ISSUE TITLE
Add "reset" filter link to member directory

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_MEMBER_PROFILE#17]
After applying a bunch of filters, I should be able to click a "Reset filter" link and have all the filters reset to their default values.
![screen shot 2016-04-15 at 9 24 40 am](https://cloud.githubusercontent.com/assets/759645/14562663/f328a126-02eb-11e6-9793-eb8e2d64ddb9.png)

**Comment by d4mation** [comment]
Just for clarification:

Are you wanting the button to just reset all the Filters without submitting the Form, or should the form be Re-Submitted with none of the Filters Applied to reset it?

**Comment by jrosebr1** [comment]
The form should be re-submitted with none of the filters applied. An easy solution would be to just create a link to `/member-directory/` since that affectively resets the form.

**Comment by d4mation** [comment]
Precisely why I asked. Sometimes they simplest solution is the best solution 👍
