### ISSUE TITLE
Adjust sizes of input fields on edit profile page

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_MEMBER_PROFILE#21]
On the edit profile page, the "About Me" and "Skills" textareas seem gigantic, while the "Linked", "GitHub", etc. inputs seem very small. In some cases, the default placeholder text is cut off. Can we default both the textarea fields and input fields to have a maximum width of 50% (or whatever else looks good)? Otherwise, the layout doesn't flow well.
![screen shot 2016-04-15 at 9 34 56 am](https://cloud.githubusercontent.com/assets/759645/14562987/a3c2b976-02ed-11e6-935b-5eb2b5dae58f.png)

**Comment by d4mation** [comment]
I tried it out with 50% width. What do you think? I think it looks better, but at the same time it feels a little... off.

![image](https://cloud.githubusercontent.com/assets/7770631/14569236/69a4fc18-030b-11e6-9e61-094abe667788.png)

Here is a little something different, with 75% width for the big textareas and 30% width for the smaller inputs below:

![image](https://cloud.githubusercontent.com/assets/7770631/14569294/c74703f2-030b-11e6-87aa-9ebf7d15b967.png)

**Comment by jrosebr1** [comment]
I definitely like this much more. The 75% and 30% looks great.
