### ISSUE TITLE
"About me" isn't being displayed properly.

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_MEMBER_PROFILE#24]
After editing the "About me" for a user, the "Completed Course" text is displayed instead of the actual text the user entered.
![screen shot 2016-04-15 at 9 41 46 am](https://cloud.githubusercontent.com/assets/759645/14563147/6f3613b4-02ee-11e6-9884-1734cff2359f.png)

**Comment by d4mation** [comment]
That's very strange. I just double checked the code and that isn't the data it should be pulling. I'll see if I can reproduce this.

**Comment by d4mation** [comment]
Could you verify this for me with the newest commit? I redid a fair amount of DOM in #23 on both the Edit and Public Profile Pages and its possible that this resolved itself.

![image](https://cloud.githubusercontent.com/assets/7770631/14575800/37ecc878-0332-11e6-90b8-03b3c6edc150.png)

**Comment by jrosebr1** [comment]
Confirmed, this is working for me now :-)
