### ISSUE TITLE
"Skills" aren't being stored.

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_MEMBER_PROFILE#25]
When I enter some text in the "Skills" field and then click "Save Changes", the changes are not being saved (or maybe they are stored in the DB, but aren't being read out again).
[skills_bug.mp4.zip](https://github.com/realbig/PL_PYIS_MEMBER_PROFILE/files/221096/skills_bug.mp4.zip)

**Comment by d4mation** [comment]
That's very odd. I remember testing this one specifically as I had to create a field for this one in the database. I'll look into this more closely.

**Comment by d4mation** [comment]
When I was working on #28 I made sure that this field was included in the save routine. Could you test this for me again on your end?

**Comment by jrosebr1** [comment]
Just to clarify: do you want me to pull down the latest version from GitHub?

**Comment by d4mation** [comment]
Yep! If you Cloned it rather than downloading the .ZIP of Master, it would be as easy as running `git pull` from within the directory.

**Comment by jrosebr1** [comment]
Closing this because the skills are now being stored.
