### ISSUE TITLE
Potential XSS?

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_MEMBER_PROFILE#28]
I'm not entirely sure, but I think the following code might be vulnerable to XSS:

<pre><meta property="twitter:title" content="<?php echo sprintf( __( "%s's Profile", $this->plugin_id ), trim( $pyis_user_data->first_name . ' ' . $pyis_user_data->last_name ) ); ?>"></pre>

For example, what would happen if I entered:

<pre>&lt;script&gt;alert("hello")&lt;/script&gt;</pre>

as my handle?

**Comment by d4mation** [comment]
You mean where the User's Name is Displayed on their Profile Page? That's a valid concern. I'll make sure I'm escaping any and all data before saving it, just to be safe.

**Comment by jrosebr1** [comment]
The first name, last name, and the GitHub, Twitter, etc. URLs. They looked vulnerable to XSS if a user was nefarious and did a direct POST to the page rather than relying on the JavaScript to validate the input.

**Comment by d4mation** [comment]
With the latest commit, before I save to the Database via `$_POST`, I'm running `wp_filter_post_kses()` on the About Me and Skills fields and `strip_tags()` on everything else. I believe that should thwart any XSS opportunities through the form. 

If they put `<script>alert( 'XSS things' );</script>` into a field now it will remove the `<script>` tags and leave the interior code, but that should be harmless.

There are libraries we could include, like [HTMLPurifier](http://htmlpurifier.org/comparison), that would rip out absolutely everything (tags and interior code), but that's a very large library to include for something that shouldn't add much benefit over what we have. [Using Regex for it wouldn't be very effective, unfortunately](http://stackoverflow.com/a/2698101).

What do you think?

**Comment by d4mation** [comment]
I just realized that it is still allowing Scripts for Administrators in _strangely_ only the Skills field (despite me directly calling `wp_filter_post_kses()` instead of checking for `unfiltered_html` like much of WP Core does), but for Subscribers it is removing `<script>` tags properly. 

I'll look into that more.

**Comment by d4mation** [comment]
Looks like still uses the backend saving routine for adding it to the database despite me manually saving it on the frontend. Weird stuff&mdash;must just be how some of the Hooks in WP line up. That's fixed now.

I put all kinds of nasty scripts in the fields to attempt to execute them (including 

```
<script script=">>><script></script><script>//"  >
/**/
alert(1);
</script
>
```

which would normally execute) and it stripped it out correctly.
