### ISSUE TITLE
Link from profile page back to member directory

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_MEMBER_PROFILE#31]
Question: If the user is on profile page, is there an easy way to link back to the member directory page they were _just_ on, including all applied filters? Currently the user has to use the back button, which isn't that big of a deal, but I think having a "Back to Member Directory" link would be great.
![screen shot 2016-04-18 at 6 43 57 am](https://cloud.githubusercontent.com/assets/759645/14601603/01160700-0531-11e6-9e6f-a38cea6ae578.png)

**Comment by d4mation** [comment]
Unfortunately there isn't a very good way to do this aside from overwriting that with JavaScript. X Theme isn't very friendly about how it handles its Breadcrumbs.

Would that be OK?

**Comment by jrosebr1** [comment]
If we can't overwrite on the PHP side, then we should include the "Back to Member Directory" link elsewhere on the page. My worry with using JavaScript for too many frontend changes is that if X Theme changes their DOM structure in the future, then functionality could start breaking.

**Comment by d4mation** [comment]
I placed the new button over with the "Public Profile" link. The button also exists in the same location on the Public Profiles.

![image](https://cloud.githubusercontent.com/assets/7770631/14618054/cadcd4a4-057e-11e6-8849-efbcee709b8c.png)

**Comment by jrosebr1** [comment]
That works for me!
