### ISSUE TITLE
"Course complete" not showing up for Administrator account

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_MEMBER_PROFILE#32]
I'm not sure if this is because I tested this page using my "Adrian" account which has "Administrator" privileges; however, for some reason the "Course complete" content was not displayed at all, but the "Course progress" was shown twice. This issue doesn't seem to happen with normal users:
![screen shot 2016-04-18 at 6 47 05 am](https://cloud.githubusercontent.com/assets/759645/14601688/8fb0b21c-0531-11e6-9fa9-7856ca83805d.png)

**Comment by d4mation** [comment]
That's really strange. I can't think of any explanation for this happening, let alone why it would make the Course Progress field show twice.

It works properly on my end using your Profile:

![image](https://cloud.githubusercontent.com/assets/7770631/14615486/db99bc22-0573-11e6-8197-bddda4276004.png)

I had the same results after Switching to your Profile and viewing both the Edit and Public screens as well.

**Comment by d4mation** [comment]
Is this with the latest commits? I'm wondering if this is related at all to #24 since I re-did some of the layout for fix that.

**Comment by jrosebr1** [comment]
Yes, this is from the commit that closed #24.

**Comment by jrosebr1** [comment]
I just tested the new version of the plugin -- the bug is indeed resolved!
![screen shot 2016-05-03 at 7 03 50 am](https://cloud.githubusercontent.com/assets/759645/14981455/4e10a4e8-10fd-11e6-8f5b-e60088d956ee.png)
