### ISSUE TITLE
Upload new avatar instructions

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_MEMBER_PROFILE#37]
I'm not sure the instructions to upload a new avatar are correct. The rotate buttons work as well as the zoom, but the "click and drag over the image" doesn't work. Is it supposed to? These instructions make it sound like the user is supposed to click and drag out a rectangular crop of what they want the profile picture to be. How about we change this section to:
1. Click the "Upload" button to select a new profile picture.
2. Crop, zoom, and position your profile picture.
3. Click "Done" to set your new profile picture.

**Comment by d4mation** [comment]
The User is able to Click and Drag over the image to reposition it within the square area. I think you're instructions are a bit clearer, so I'll be sure to swap them in.

**Comment by jrosebr1** [comment]
Indeed, you are able to click and drag to reposition the profile picture; however, the term "click and drag" has a different meaning to people who work in computer vision (which is what the PyImageSearch Gurus site is comprised of). To them, "click and drag" means drawing out a "bounding box" surrounding an object in an image, like this:

http://www.pyimagesearch.com/wp-content/uploads/2015/01/mouse-event-crop-raptor.jpg
