### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by d4mation** [realbig/PL_PYIS_MEMBER_PROFILE#4]
@jrosebr1,

Is there any sample data available? While it isn't critical to the completion of the plugin, it would make testing more complete and thorough if there is an export of Users in your system that I could use to test against.

**Comment by jrosebr1** [comment]
@d4mation- I can certainly dump the users to a CSV file, that's not an issue. Do you have a recommended way to do that?

**Comment by d4mation** [comment]
I've personally never messed with exporting Users to a CSV. I believe something like [this plugin](https://wordpress.org/plugins/export-user-data/) would handle it for you and would handle all the User Meta as well. I could then use another plugin to import them on my end.

I usually just export the `wp_users` and `wp_usermeta` tables from the database, as I can just import those directly into a local database on my computer.

Whichever you're most comfortable doing works for me. :+1:

**Comment by jrosebr1** [comment]
Perfect, I'll go ahead and export the `wp_users` and `wp_usermeta` tables and them them uploaded within the hour.

**Comment by jrosebr1** [comment]
Please find the tables attached.

[tables.zip](https://github.com/realbig/PL_PYIS_MEMBER_PROFILE/files/194402/tables.zip)

**Comment by d4mation** [comment]
Thank you! If I realize I need some more data, I'll let you know!

**Comment by d4mation** [comment]
I've been making some great progress with this, but I'm realizing now that I don't have quite all the data I need.

Would you be opposed to giving me a full database dump? I figure that should cover any and all bases that I'd need to cover. 

That way I can ensure things like Course Completion and stuff are working correctly. I wrongly assumed that would be stored in `user_meta`, but it seems that LearnDash stores things in its own Tables.

**Comment by jrosebr1** [comment]
What other data do you need? There are a lot of production settings inside the database, so to be honest, I would prefer if we could avoid doing a full DB dump.

**Comment by d4mation** [comment]
Any MemberPress settings and LearnDash settings should be all that I need. 

Unfortunately, MemberPress is locking me out entirely as I don't have a License Key. However, it seems that most of the data I need to pull is from LearnDash so hopefully that won't be a problem.

I want to ensure that I can grab their Course Completion properly primarily. 

Looking at table names, I _think_ these are all that I'd need:
- `wp_mepr_events`
- `wp_mepr_jobs`
- `wp_mepr_tax_rates`
- `wp_mepr_tax_rate_locations`
- `wp_mepr_transactions`
- `wp_wp_pro_quiz_category`
- `wp_wp_pro_quiz_form`
- `wp_wp_pro_quiz_lock`
- `wp_wp_pro_quiz_master`
- `wp_wp_pro_quiz_prerequisite`
- `wp_wp_pro_quiz_question`
- `wp_wp_pro_quiz_statistic`
- `wp_wp_pro_quiz_statistic_ref`
- `wp_wp_pro_quiz_template`
- `wp_wp_pro_quiz_toplist`

I just checked `wp_options` and there doesn't seem to be anything implementation-specific in there for either MemberPress or LearnDash.

Sorry to be asking for so much data! I want to be certain that the plugin will have access to what it needs to on your production site.

**Comment by jrosebr1** [comment]
No problem, I'll make sure that I get you the tables. My primary concern is that I don't want endpoints to somehow get messed up. The PyImageSearch Gurus site runs in production mode, and the last thing I would want is for data to be sent to the wrong server.

**Comment by jrosebr1** [comment]
Here you go.
[moar_tables.zip](https://github.com/realbig/PL_PYIS_MEMBER_PROFILE/files/200290/moar_tables.zip)

**Comment by jrosebr1** [comment]
Also, I recommended talking to Kyle (@brashrebel) about getting licenses for both LearnDash and Memberpress. Did you guys not go ahead and get them?

**Comment by d4mation** [comment]
Ah, that makes sense. I understand. I am ensuring [to replace all mentions of your domain when I import it](https://interconnectit.com/products/search-and-replace-for-wordpress-databases/), but you can never be too careful.

I just got the necessary license keys from @brashrebel.

I hate to ask again, but it looks like I need just a little more data still.

Could you get me an export of your Content from the WP Export menu? I specifically need the following, but if you'd rather just do a single export of "All Content", that works fine as well.
- `Coupons`
- `Groups`
- `Memberships`
- `Reminders`
- `Rules`
- `Subscriptions`
- `Courses`
- `Lessons`
- `Quizzes`
- `Assignments`
- `LearnDash Groups`
- `Topics`
- `Certificates`
- `Transactions`

**Comment by jrosebr1** [comment]
Yes, please make sure that all mentions of the PyImageSearch domain are removed. This is something that I was _really_ hoping we could avoid since it can not only lead to some nasty, hard to find bugs, but it could also hurt the consistency of the data itself on the production server.

Also, where is the "WP Export" menu?

**Comment by d4mation** [comment]
Ah, sorry, you'll find the "WP Export Menu" under:

WP Admin Dashboard -> Tools -> Export 

Then just export it as an XML if it gives you the option if you could. Thanks!

**Comment by jrosebr1** [comment]
The complete "All Content" export is 30MB. Here is a link to my Dropbox. Please let me know when you have downloaded it so I can delete it:

https://www.dropbox.com/s/hywq8btn3unm4wl/pyimagesearchgurus.wordpress.2016-04-02.xml?dl=0

**Comment by d4mation** [comment]
Downloaded and imported.

Now I'm seeing all the data that I was looking for! Thank you so much!
