### ISSUE TITLE
Add ability to upload a User Profile Image

### ISSUE THREAD

**Issue by d4mation** [realbig/PL_PYIS_MEMBER_PROFILE#8]
WP doesn't support this out of the box as far as I can tell. This will need to be added in a fluid manner that isn't confusing (Replacing the current field preferably, and showing their Gravatar if they have one).

**Comment by d4mation** [comment]
@jrosebr1 

How would you feel about implementing another plugin to handle User Profile Images? [WP User Avatar](https://wordpress.org/plugins/wp-user-avatar/) seems to handle everything this would need.

I wanted to avoid another dependency if possible and to use built-in functions for everything, but WordPress' Media Uploader seems to be very particular about how it handles things and has limited ability to change it.

I was able to get everything to work using the built in Uploader aside from cropping.

If I grant `subscribers` the `edit_post` and `delete_post` capabilities, they are then able to crop their Avatars.

However, they aren't able to do that from the Front-end. It redirects them to the Backend to the Media Attachment screen to do it.

This screen in particular:
![image](https://cloud.githubusercontent.com/assets/7770631/14332526/fba450b4-fc17-11e5-88b6-f0af77795c83.png)

That's definitely no good since normally Subscribers don't seem to normally have an Admin Bar with this configuration. This gives them an Admin Bar and even allows them to _create Posts_.

Most methods say to use the `user_has_cap` Filter to restrict their abilities to only `attachments`, but since it is running through a weird AJAX Modal it doesn't seem to make a difference in this case, as `current_user_can` always returns `false` for editing an `attachment`.

I have successfully made it so that they are only able to view/set an Avatar that they have added on their own and they are also able to revert to a Gravatar seamlessly.

**Comment by jrosebr1** [comment]
I'm okay with using another plugin, that's not a problem. But I am definitely against having to hit the WordPress backend, I would like to avoid that at all costs.

**Comment by d4mation** [comment]
I ended up running into some issues with WP User Avatar as well, so I'm implementing my own non-built-in solution.

![image](https://cloud.githubusercontent.com/assets/7770631/14357474/d86d8c7e-fcb6-11e5-9c90-cdcfadf0a76e.png)

It uses [Foundation's Reveal Modal](http://foundation.zurb.com/sites/docs/reveal.html) and [cropit](http://scottcheng.github.io/cropit/).

Cropit saves the changes to a Data-URI, so all I need to do is to "download" that when saving it to the server.

I'm about to start the Server-side implementation for that. I was wondering how you felt about saving the Avatars into a new folder within `wp-uploads`? Something like `/wp-uploads/pyis-avatars` and then having them saved as `<username>.jpeg`?

That way if they change their Avatar a lot, it will overwrite any previous one they have saved.

**Comment by jrosebr1** [comment]
I definitely like the idea of using a dedicated `avatars` directory in
`wp-uploads`. That will absolutely keep things more organized, especially
with the `<username>.jpg` filename. Great suggestion!

**Comment by d4mation** [comment]
This has been implemented! Now Avatars will be stored at `wp-content/uploads/pyis-avatars/<username>.png`.

The directory name can be changed with the `pyis_avatars_directory` filter, but it will only place it under `wp-content/uploads` as the way read/write permissions work within WordPress we can pretty much guarantee that there will be no problems storing files there.

The folder is created at Plugin Activation, so the Filter would need to be in place before Plugin activation (and then the Filter would need to stay in place so the Plugin knows where to look for Avatars).
